#version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/:/app/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    #Uncommentthe next line in case o neet to connect to local service, a local postgres db for example
    #network_mode: host
    ports:
      - 8000:8000
